[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; --- WAŻNE: OPTYMALIZACJA PAMIĘCI ---
; huge_app.csv daje ~3MB na kod aplikacji (zamiast 1.2MB).
; Nasz kod v15 jest spory, więc to jest KONIECZNE, żeby się zmieścił!
board_build.partitions = huge_app.csv

; --- KONFIGURACJA USB (Dla ESP32-C3 SuperMini) ---
; To sprawia, że Serial.print idzie prosto do konsoli przez USB
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; --- BIBLIOTEKI (POPRAWIONE) ---
lib_deps =
    ; Używamy forka od mathieucarbou - działa stabilnie na nowych ESP32
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git
    ; Biblioteka do zegara RTC DS3231
    adafruit/RTClib @ ^2.1.3
    ; Biblioteki systemowe (Wire dla I2C jest wbudowane, ale czasem warto wymusić)
    Wire

; --- USTAWIENIA KOMPILATORA ---
; Ignorujemy wbudowany WebServer, bo używamy Asynca
lib_ignore = WebServer
; Głębokie szukanie zależności (naprawia błędy linkera)
lib_ldf_mode = deep

; --- USTAWIENIA PORTU ---
; Zapobiega resetowaniu płytki przy otwarciu monitora (Kluczowe dla C3!)
monitor_dtr = 0
monitor_rts = 0

; Porty - upewnij się, że to Twój numer!
upload_port = COM17
monitor_port = COM17